### ISSUE TITLE
Todo: Add new todo 

### ISSUE THREAD

**Issue by kymiddleton** [kymiddleton/momentum.clone#5]
##Description:
- User wants to add something to the to do list

##Acceptance Criteria:
- [x]  when user clicks on "Todo", box appears 
- [x]  when user clicks  "New todo" entry field appears
- [x] when user presses "enter", add todo to list
